### ISSUE TITLE
Storage resolution error

### ISSUE THREAD

**Issue by lubegamark** [joker1007/fluent-plugin-cloudwatch-put#1]
Whenever I try using this plugin I get

`2017-11-13 11:23:31 +0300 [warn]: #0 failed to flush the buffer. retry_time=5 next_retry_seconds=2017-11-13 11:23:31 +0300 chunk="55dd8f6e3f7d891e1482293cbf73b7db" error_class=ArgumentError error="unexpected value at params[:metric_data][0][:storage_resolution]"`

Any help would be appreciated

**Comment by joker1007** [comment]
Thank you for the report!
Please tell me aws-sdk version in your environment.

**Comment by lubegamark** [comment]
When I run td-agent with trace logging, 
**aws-sdk-ruby2/2.9.19**
My CLI version
**aws-cli/1.11.112**
The td-agent version is **v0.14**

My config looks like this

`<match server1>
  @type cloudwatch_put

  <buffer tag, key1>
    path cloudwatch.*.buffer
    flush_interval 1m
  </buffer>

  aws_key_id xxxx
  aws_sec_key xxxx

  region us-east-1

  namespace "Dummy/Namespace"
  metric_name ${tag[1]}
  unit None
  value_key value
  storage_resolution 1
  #use_statistic_sets

  <dimensions>
    name method
    value ${key1}
  </dimensions>
</match>`

**Comment by joker1007** [comment]
I reproduced this error.
because your aws-sdk version is old. the version does not support high resolution metric.

Please update aws-sdk to latest 2.x.

I will update gemspec for version constraint.

**Comment by lubegamark** [comment]
Thank you. Let me try with a newer SDK

**Comment by lubegamark** [comment]
It worked flawlessly with aws-sdk-core 2.10.86
